### ISSUE TITLE
Latest version installable from PyPI is 0.1.1

### ISSUE THREAD

**Issue by supervacuo** [rfkrocktk/django-locality#9]
```
$ pip install -v django-locality==0.2.2
Downloading/unpacking django-locality==0.2.2
  Could not fetch URL http://pypi.python.org/simple/django-locality/0.2.2: HTTP Error 404: Not Found
  Will skip URL http://pypi.python.org/simple/django-locality/0.2.2 when looking for download links for django-locality==0.2.2
  Ignoring link https://pypi.python.org/packages/source/d/django-locality/django-locality-0.1.1.tar.gz#md5=e9aba5177a8ab82bfdec49934b21bd7b (from https://pypi.python.org/simple/django-locality/), version 0.1.1 doesn't match ==0.2.2
  Could not find a version that satisfies the requirement django-locality==0.2.2 (from versions: )
No distributions matching the version for django-locality==0.2.2
Exception information:
Traceback (most recent call last):
  File "/home/carl/.virtualenvs/coolfarmtool/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/basecommand.py", line 104, in main
    status = self.run(options, args)
  File "/home/carl/.virtualenvs/coolfarmtool/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/commands/install.py", line 245, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/home/carl/.virtualenvs/coolfarmtool/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/req.py", line 978, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/home/carl/.virtualenvs/coolfarmtool/lib/python2.7/site-packages/pip-1.1-py2.7.egg/pip/index.py", line 186, in find_requirement
    raise DistributionNotFound('No distributions matching the version for %s' % req)
DistributionNotFound: No distributions matching the version for django-locality==0.2.2

Storing complete log in /home/carl/.pip/pip.log
```

and:

```
$ pip install django-locality
Downloading/unpacking django-locality
  Downloading django-locality-0.1.1.tar.gz
  Running setup.py egg_info for package django-locality
  ...
```

**Comment by yourcelf** [comment]
+1, been almost 2 years. Is this project abandoned?

**Comment by rfkrocktk** [comment]
It hasn't been abandoned. I'll attempt to dig up my PyPI credentials and publish tomorrow.

**Comment by rfkrocktk** [comment]
Actually, I'm seeing it here: https://pypi.python.org/pypi/django-locality/0.2.2

What seems to be the problem @yourcelf?

**Comment by supervacuo** [comment]
I can still reproduce the original problem in a clean Python 2.7 virtualenv. Issue seems to be 

    Skipping link https://pypi.python.org/packages/2.7/d/django-locality/django_locality-0.2.2-py2.7.egg#md5=96f36fd35e077dedb7fa8074c437f67b (from https://pypi.python.org/simple/django-locality/); unsupported archive format: .egg

I am on GNU/Linux (Fedora 23); it's looking for a `.tar.gz` package, I think.

**Comment by supervacuo** [comment]
Full output:

```
$ pip install -v django-locality==0.2.2
Collecting django-locality==0.2.2
  Getting page https://pypi.python.org/simple/django-locality/
  1 location(s) to search for versions of django-locality:
  * https://pypi.python.org/simple/django-locality/
  Getting page https://pypi.python.org/simple/django-locality/
  Analyzing links from page https://pypi.python.org/simple/django-locality/
    Skipping link https://pypi.python.org/packages/2.7/d/django-locality/django_locality-0.1-py2.7.egg#md5=90d60e01f6e225e6179f311a50c1aab1 (from https://pypi.python.org/simple/django-locality/); unsupported archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/d/django-locality/django_locality-0.1.1-py2.7.egg#md5=0a189b49804792b4fb018bec5c14fba1 (from https://pypi.python.org/simple/django-locality/); unsupported archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/d/django-locality/django_locality-0.1.2-py2.7.egg#md5=2b118c647eddd7e60095e442e582d677 (from https://pypi.python.org/simple/django-locality/); unsupported archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/d/django-locality/django_locality-0.2.0-py2.7.egg#md5=be4ad0a843ef29ea13deec8ab34a1f28 (from https://pypi.python.org/simple/django-locality/); unsupported archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/d/django-locality/django_locality-0.2.1-py2.7.egg#md5=8c88b4de912952919e057fe3899793c9 (from https://pypi.python.org/simple/django-locality/); unsupported archive format: .egg
    Skipping link https://pypi.python.org/packages/2.7/d/django-locality/django_locality-0.2.2-py2.7.egg#md5=96f36fd35e077dedb7fa8074c437f67b (from https://pypi.python.org/simple/django-locality/); unsupported archive format: .egg
    Found link https://pypi.python.org/packages/source/d/django-locality/django-locality-0.1.1.tar.gz#md5=e9aba5177a8ab82bfdec49934b21bd7b (from https://pypi.python.org/simple/django-locality/), version: 0.1.1
  Could not find a version that satisfies the requirement django-locality==0.2.2 (from versions: 0.1.1)
Cleaning up...
No matching distribution found for django-locality==0.2.2
Exception information:
Traceback (most recent call last):
  File "/data/.virtualenvs/tmp-e8f4a4b2569f31ad/lib/python2.7/site-packages/pip/basecommand.py", line 211, in main
    status = self.run(options, args)
  File "/data/.virtualenvs/tmp-e8f4a4b2569f31ad/lib/python2.7/site-packages/pip/commands/install.py", line 294, in run
    requirement_set.prepare_files(finder)
  File "/data/.virtualenvs/tmp-e8f4a4b2569f31ad/lib/python2.7/site-packages/pip/req/req_set.py", line 334, in prepare_files
    functools.partial(self._prepare_file, finder))
  File "/data/.virtualenvs/tmp-e8f4a4b2569f31ad/lib/python2.7/site-packages/pip/req/req_set.py", line 321, in _walk_req_to_install
    more_reqs = handler(req_to_install)
  File "/data/.virtualenvs/tmp-e8f4a4b2569f31ad/lib/python2.7/site-packages/pip/req/req_set.py", line 461, in _prepare_file
    req_to_install.populate_link(finder, self.upgrade)
  File "/data/.virtualenvs/tmp-e8f4a4b2569f31ad/lib/python2.7/site-packages/pip/req/req_install.py", line 250, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/data/.virtualenvs/tmp-e8f4a4b2569f31ad/lib/python2.7/site-packages/pip/index.py", line 571, in find_requirement
    'No matching distribution found for %s' % req
DistributionNotFound: No matching distribution found for django-locality==0.2.2
```

**Comment by yourcelf** [comment]
Ditto with clean python3 virtualenv:

    $ pip install django-locality==0.2.2
    Downloading/unpacking django-locality==0.2.2
      Could not find a version that satisfies the requirement django-locality==0.2.2 (from versions: 0.1.1)
    Cleaning up...
    No distributions matching the version for django-locality==0.2.2
    Storing debug log for failure in /home/tc1/.pip/pip.log

    $ pip install django-locality
    Downloading/unpacking django-locality
      Downloading django-locality-0.1.1.tar.gz
      Running setup.py (path:/home/tc1/git/workerfatalities/venv/build/django-locality/setup.py) egg_info for package django-locality
        
    Requirement already satisfied (use --upgrade to upgrade): Django>=1.3.0 in ./venv/lib/python3.4/site-packages (from django-locality)
    Requirement already satisfied (use --upgrade to upgrade): setuptools in ./venv/lib/python3.4/site-packages (from django-locality)
    Installing collected packages: django-locality
      Running setup.py install for django-locality
        
    Successfully installed django-locality
    Cleaning up...
    $ 

0.2.2 reports no version available; and without specifying, I get 0.1.1.

**Comment by rfkrocktk** [comment]
@supervacuo @yourcelf I have just uploaded a new source package as well as an egg for Python 2.7. I'm going to try and download it now using pip.

**Comment by rfkrocktk** [comment]
I have tested it locally and I'm able to do `pip install django-locality==0.2.2` without issue.

PyPI was renaming my packages and doing weird things, so I had to upload manually. I have also now included a source package to PyPI, which should fix things.

**Comment by yourcelf** [comment]
Can confirm that it works for me now with python3. Thanks.

**Comment by supervacuo** [comment]
working on 2.7, too. thanks @rfkrocktk!

**Comment by rfkrocktk** [comment]
Hell yes! Closing.
